name: 'Set Environment Variables'
description: 'Set Environment Variables'

inputs:
  variablesPath:
    description: 'The path to the YAML file that contains the key value pairs for environment variables'
    required: true

runs:
  using: 'composite'
  steps:

    # [Set environment variables] task(s)
    # ---------------
    - name: 'Set environment variables'
      id: set-env-variables
      shell: pwsh
      run: |
        # Grouping task logs
        Write-Output '::group::Set environment variables'

        # Load used functions
        . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'sharedScripts' 'Add-YamlListToFile.ps1')

        $functionInput = @{
          InputFilePath   = '${{ inputs.variablesPath }}'
          ListName        = 'variables'
          OutputFilePath  =  $Env:GITHUB_ENV
        }

        Write-Verbose "Invoke task with" -Verbose
        Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

        # Convert YAML Variable File to Environment Variables
        Add-YamlListToFile @functionInput -Verbose

        Write-Output '::endgroup::'
