name: 'Publish'

on:
  workflow_dispatch:
    inputs:
      foo:
        type: boolean
        description: 'bar'
        required: false
        default: true

  push:
    branches:
      - mvp
    paths:
      - '.github/actions/templates/**'
      - '.github/workflows/publish.yml'
      - 'modules/**'

env:
  variablesPath: 'settings.yml'

  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  ARM_SUBSCRIPTION_ID: '${{ secrets.ARM_SUBSCRIPTION_ID }}'
  ARM_MGMTGROUP_ID: '${{ secrets.ARM_MGMTGROUP_ID }}'
  ARM_TENANT_ID: '${{ secrets.ARM_TENANT_ID }}'

jobs:
  job_publish_modules:
    name: 'Pull, collect and publish'
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.event.inputs.foo == 'true'
    runs-on: ubuntu-20.04
    steps:
      - name: 'Pull Azure/ResourceModules'
        uses: actions/checkout@v3
        with:
          repository: 'Azure/ResourceModules'
          path: carml
      - name: 'Checkout Azure/resource-modules-registry'
        uses: actions/checkout@v3
        with:
          clean: false
          path: carmr
      - name: "Let's have a look"
        shell: pwsh
        run: |
          dir env:
          pwd
          gci
