name: 'Publish'

on:
  workflow_dispatch:
    inputs:
      foo:
        type: boolean
        description: 'bar'
        required: false
        default: true

  push:
    branches:
      - main
    paths:
      - '.github/actions/templates/**'
      - '.github/workflows/publish.yml'
      - 'modules/**'

env:
  variablesPath: 'settings.yml'

  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  ARM_SUBSCRIPTION_ID: '${{ secrets.ARM_SUBSCRIPTION_ID }}'
  ARM_MGMTGROUP_ID: '${{ secrets.ARM_MGMTGROUP_ID }}'
  ARM_TENANT_ID: '${{ secrets.ARM_TENANT_ID }}'

jobs:
  job_pull_modules:
    name: 'Publishing'
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          repository: 'Azure/ResourceModules'
          fetch-depth: 0
  job_publish_modules:
    name: 'Publishing'
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.event.inputs.foo == 'true'
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
